%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Code generated by Dr. Komlan Atitey/ NIH-NIEHS Biostatistics and Computational Biology Branch.
%  This code is written to assess the proliferation of lymphocytes under the MMQE-Agent based model presented 
%  in the: "Mathematical modeling of proliferative immune response initiated by interactions between classical
%  antigen presenting cells under joint antagonistic IL-2 and IL-4 signaling".
                                                      %%%%%%
% Any inquiries for explanation or usage of this code could be addressed to the author via the address below:
% komlan.atitey@nih.gov 
% atiteydavidkomlan@yahoo.fr
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clc
clear all

%% %%%%%%%%%%% parameters defined in Table 2
Nth0 = 805;
Mthd = 9.16e-8;
r1 = 3.8e7;
r2 = 18.6e-4;
r3 = 23.46e7;
r4 = 2.09e-4;
r5 = 1.8e-11; %2.08e-16; %1.8e-11;
r6 = 7.5e-2;
r7 = 1;
r8 = 1.2;
rtrue = [r1 r2 r3 r4 r5 r6 r7 r8]; 
y0 = [0 0 0 0 Nth0 0 3 5];
 
%% %%%%%%%%%%% Time unit
N = 7200; % length of time unit in minutes
tspan = linspace(0,N); % time scaling

%% %%%%%%%%%%% DC APC activator
soltrue_1 = ode45(@(t,y)DC_APC(t,y,rtrue),tspan,y0);
yvalstrue_1 = deval(soltrue_1,tspan);

%% %%%%%%%%%%% Bcell APC activator
soltrue_2 = ode45(@(t,y)Bcell_APC(t,y,rtrue),tspan,y0);
yvalstrue_2 = deval(soltrue_2,tspan);

%% %%%%%%%%%%% DC and Bcell APCs activators
soltrue_3 = ode45(@(t,y)DC_Bcell_APCs(t,y,rtrue),tspan,y0);
yvalstrue_3 = deval(soltrue_3,tspan);

%% %%%%%%%%%%% plotting the downregulation of IL-2 by IL-4 
figure(1)  
plot(tspan,yvalstrue_1(1,:))
hold on
plot(tspan,yvalstrue_1(2,:))
legend('Unbound IL-4R','Bound IL-4R')
xlabel('Proliferation time');
ylabel('Number of IL-4 receptor')
 
%% 
figure(2)
plot(tspan,yvalstrue_1(3,:))
hold on
plot(tspan,yvalstrue_1(4,:))
legend('Unbound IL-2R','Bound IL-2R')
xlabel('Proliferation time');
ylabel('Number of IL-2 receptor')
%%%%%%%%%%%%%%%%%%%%%%%% 
